import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { canonicalPublicCategoryId, isPublicCategoryInGroup, publicCategorySymbol, resolvePublicCategory } from "./public-category-rules.mjs";
const fixturesUrl = new URL("../shared/public-category-fixtures.json", import.meta.url);
const fixtures = JSON.parse(readFileSync(fileURLToPath(fixturesUrl), "utf8"));
for (const fixture of fixtures.cases) assert.deepEqual(resolvePublicCategory(fixture.event), fixture.expected, `shared fixture failed: ${fixture.name}`);
assert.equal(canonicalPublicCategoryId({ id: "formacion-taller", label: "Formación / taller" }), "cursos-talleres-campus");
assert.equal(canonicalPublicCategoryId({ label: "Cursos, talleres y experiencias" }), "cursos-talleres-campus");
assert.equal(canonicalPublicCategoryId({ id: "cursos-talleres-experiencias" }), "cursos-talleres-campus");
assert.equal(isPublicCategoryInGroup({ label: "Cursos, talleres y experiencias" }, "training"), true);
assert.equal(publicCategorySymbol({ id: "cursos-talleres-campus" }), "✦");
console.log("PUBLIC_CATEGORY_RULES_OK");
