from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "shared" / "public-category-taxonomy.json"
TARGET = ROOT / "app" / "public-category-taxonomy.generated.mjs"


def render_module(payload: dict) -> str:
    serialized = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
    return (
        "// AUTO-GENERATED by scripts/generate_public_category_module.py.\n"
        "// Edit shared/public-category-taxonomy.json instead.\n\n"
        f"export const PUBLIC_CATEGORY_TAXONOMY = Object.freeze({serialized});\n\n"
        "export const PUBLIC_CATEGORIES = Object.freeze(PUBLIC_CATEGORY_TAXONOMY.categories);\n"
        "export const PUBLIC_CATEGORY_ALIASES = Object.freeze(PUBLIC_CATEGORY_TAXONOMY.aliases);\n"
        "export const PUBLIC_CATEGORY_LABEL_ALIASES = Object.freeze(PUBLIC_CATEGORY_TAXONOMY.label_aliases);\n"
        "export const PUBLIC_CATEGORY_GROUPS = Object.freeze(PUBLIC_CATEGORY_TAXONOMY.groups);\n"
        "export const PUBLIC_EVENT_TYPE_LABELS = Object.freeze(PUBLIC_CATEGORY_TAXONOMY.event_type_labels);\n"
    )


def expected_text() -> str:
    payload = json.loads(SOURCE.read_text(encoding="utf-8"))
    return render_module(payload)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated module is stale")
    args = parser.parse_args()

    expected = expected_text()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != expected:
            raise SystemExit(
                "PUBLIC_CATEGORY_MODULE_STALE: run python scripts/generate_public_category_module.py"
            )
        print("PUBLIC_CATEGORY_MODULE_OK")
        return 0

    TARGET.write_text(expected, encoding="utf-8")
    print(f"PUBLIC_CATEGORY_MODULE_WRITTEN path={TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
