from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "shared" / "event-semantics.json"
TARGET = ROOT / "app" / "event-semantics.generated.mjs"


def render_module(payload: dict) -> str:
    serialized = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
    return (
        "// AUTO-GENERATED by scripts/generate_event_semantics_module.py.\n"
        "// Edit shared/event-semantics.json instead.\n\n"
        f"export const EVENT_SEMANTICS = Object.freeze({serialized});\n"
    )


def expected_text() -> str:
    return render_module(json.loads(SOURCE.read_text(encoding="utf-8")))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated module is stale")
    args = parser.parse_args()
    expected = expected_text()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != expected:
            raise SystemExit(
                "EVENT_SEMANTICS_MODULE_STALE: run python scripts/generate_event_semantics_module.py"
            )
        print("EVENT_SEMANTICS_MODULE_OK")
        return 0
    TARGET.write_text(expected, encoding="utf-8")
    print(f"EVENT_SEMANTICS_MODULE_WRITTEN path={TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
