from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[2]
APP = ROOT / "app"
MANIFEST_PATH = APP / "service-worker-assets.generated.js"
VENUE_BRIDGE_PATH = APP / "venue-registry.generated.mjs"
RELEASE_PATH = APP / "release-version.js"
INDEX_PATH = APP / "index.html"

ENTRYPOINTS = (
    APP / "index.html",
    APP / "app.js",
    APP / "pwa.js",
    APP / "service-worker.js",
    APP / "mis-planes.html",
    APP / "proponer-fuente.html",
)
TEXT_SUFFIXES = {".js", ".mjs", ".css", ".html", ".webmanifest", ".json"}
RELEASE_RE = re.compile(r"const\\s+RELEASE\\s*=\\s*(\\d+)\\s*;")
RELEASE_ASSETS = ("./app.js", "./map-navigation-enhancer.js")
CACHEABLE_SUFFIXES = TEXT_SUFFIXES | {".svg", ".png", ".jpg", ".jpeg", ".webp", ".ico"}
REFERENCE_RE = re.compile(r"[\"']((?:\.\.?/)[^\"'?#]+(?:\?[^\"']*)?)[\"']")

VENUE_BRIDGE = '''// Generated runtime bridge for app/data/venue-registry.json.\n// Venue facts live only in the JSON registry; do not hardcode them here.\nasync function loadVenueRegistry() {\n  const url = new URL("./data/venue-registry.json", import.meta.url);\n  if (url.protocol === "file:") {\n    const { readFile } = await import("node:fs/promises");\n    return JSON.parse(await readFile(url, "utf8"));\n  }\n  const response = await fetch(url, { cache: "no-store" });\n  if (!response.ok) throw new Error(`Venue registry HTTP ${response.status}`);\n  return response.json();\n}\n\nexport const VENUE_REGISTRY = Object.freeze(await loadVenueRegistry());\nexport const VENUES = Object.freeze(VENUE_REGISTRY.venues || []);\nexport const EVENT_LOCATION_OVERRIDES = Object.freeze(VENUE_REGISTRY.event_location_overrides || []);\n'''

SEED_ASSETS = {
    "./",
    "./index.html",
    "./release-version.js",
    "./service-worker-assets.generated.js",
    "./venue-registry.generated.mjs",
    "./data/venue-registry.json",
    "./data/release-bundle.json",
    "./manifest.webmanifest",
}


def manifest_url(path: Path) -> str:
    rel = os.path.relpath(path, APP).replace(os.sep, "/")
    if not rel.startswith("."):
        rel = "./" + rel
    return rel


def local_reference(base: Path, ref: str) -> Path | None:
    clean = urlsplit(ref).path
    if not clean or clean.startswith("/"):
        return None
    candidate = (base.parent / clean).resolve()
    try:
        candidate.relative_to(ROOT.resolve())
    except ValueError:
        return None
    return candidate


def discover_runtime_assets() -> set[str]:
    discovered = set(SEED_ASSETS)
    queue = [path.resolve() for path in ENTRYPOINTS if path.exists()]
    seen: set[Path] = set()
    while queue:
        path = queue.pop()
        if path in seen or not path.exists() or not path.is_file():
            continue
        seen.add(path)
        if path.suffix.lower() not in TEXT_SUFFIXES:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for ref in REFERENCE_RE.findall(text):
            target = local_reference(path, ref)
            if not target or not target.exists() or not target.is_file():
                continue
            if target.suffix.lower() not in CACHEABLE_SUFFIXES:
                continue
            discovered.add(manifest_url(target))
            if target.suffix.lower() in TEXT_SUFFIXES:
                queue.append(target)
    return discovered


def parse_manifest(text: str) -> list[str]:
    match = re.search(r"__VIVAMOS_SHELL_ASSETS__\s*=\s*Object\.freeze\((\[[\s\S]*?\])\)", text)
    if not match:
        raise ValueError("generated shell manifest payload not found")
    return json.loads(match.group(1))


def render_manifest(assets: set[str]) -> str:
    ordered = ["./"] + sorted(asset for asset in assets if asset != "./")
    payload = json.dumps(ordered, ensure_ascii=False, indent=2)
    return (
        "// Generated by app/scripts/generate_runtime_contracts.py. Do not edit by hand.\n"
        "(() => {\n"
        f"  globalThis.__VIVAMOS_SHELL_ASSETS__ = Object.freeze({payload.replace(chr(10), chr(10) + '  ')});\n"
        "})();\n"
    )


def existing_assets() -> set[str]:
    if not MANIFEST_PATH.exists():
        return set()
    return set(parse_manifest(MANIFEST_PATH.read_text(encoding="utf-8")))


def validate_local_assets(assets: set[str]) -> list[str]:
    missing = []
    for asset in assets:
        if asset == "./":
            continue
        path = (APP / asset.split("?", 1)[0]).resolve()
        if not path.exists():
            missing.append(asset)
    return sorted(missing)


def canonical_release() -> int:
    match = RELEASE_RE.search(RELEASE_PATH.read_text(encoding="utf-8"))
    if not match:
        raise ValueError("canonical PWA release not found")
    return int(match.group(1))


def synchronize_release_asset_versions(text: str, release: int) -> str:
    for asset in RELEASE_ASSETS:
        pattern = re.compile(rf'({re.escape(asset)})(?:\\?v=\\d+)?')
        if len(pattern.findall(text)) != 1:
            raise ValueError(f"release asset must appear exactly once in index: {asset}")
        text = pattern.sub(rf"\\1?v={release}", text)
    return text


def release_asset_version_errors() -> list[str]:
    release = canonical_release()
    index = INDEX_PATH.read_text(encoding="utf-8")
    expected = synchronize_release_asset_versions(index, release)
    if index == expected:
        return []
    return [f"index release asset keys are stale; run --write for release {release}"]


def write_contracts() -> None:
    INDEX_PATH.write_text(
        synchronize_release_asset_versions(INDEX_PATH.read_text(encoding="utf-8"), canonical_release()),
        encoding="utf-8",
    )
    VENUE_BRIDGE_PATH.write_text(VENUE_BRIDGE, encoding="utf-8")
    # Generated runtime assets are derived only from the current entrypoint graph.
    # Never union with the previous manifest: doing so makes deleted/retired
    # modules immortal in the PWA cache contract.
    assets = discover_runtime_assets()
    MANIFEST_PATH.write_text(render_manifest(assets), encoding="utf-8")


def check_contracts() -> None:
    errors: list[str] = release_asset_version_errors()
    if VENUE_BRIDGE_PATH.read_text(encoding="utf-8") != VENUE_BRIDGE:
        errors.append("venue-registry.generated.mjs is stale")
    committed = existing_assets()
    discovered = discover_runtime_assets()
    missing_from_manifest = sorted(discovered - committed)
    if missing_from_manifest:
        errors.append("runtime assets missing from generated manifest: " + ", ".join(missing_from_manifest))
    duplicates = []
    if MANIFEST_PATH.exists():
        rows = parse_manifest(MANIFEST_PATH.read_text(encoding="utf-8"))
        duplicates = sorted({row for row in rows if rows.count(row) > 1})
    if duplicates:
        errors.append("duplicate generated assets: " + ", ".join(duplicates))
    missing_files = validate_local_assets(committed)
    if missing_files:
        errors.append("generated manifest points to missing files: " + ", ".join(missing_files))
    if errors:
        raise SystemExit("RUNTIME_CONTRACTS_STALE\n" + "\n".join(errors))
    print(f"RUNTIME_CONTRACTS_OK assets={len(committed)} discovered={len(discovered)}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate/check the canonical venue bridge and PWA shell asset manifest.")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write_contracts()
        print("RUNTIME_CONTRACTS_WRITTEN")
    else:
        check_contracts()


if __name__ == "__main__":
    main()
